name: Godrick CI/CD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run_builder:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Conduit
        run: |
         sudo apt-get install -y libopenmpi-dev
         mkdir conduit
         cd conduit
         git clone --recursive https://github.com/llnl/conduit.git .
         mkdir build
         cd build
         cmake ../src -DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../conduit_install -DENABLE_MPI:BOOL=TRUE
         make -j
         make install 
         ls $PWD/../../conduit_install
      - name: Install Conan
        run: |
          echo $PWD
          sudo apt install -y python3-pip
          pip3 install conan==1.60
      - name: Configure Godrick
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          export CONDUIT_PREFIX=${{ github.workspace }}/conduit_install
          ../run_cmake_script.sh
      - name: Compile Godrick
        run: |
          cd ${{ github.workspace }}/build
          make -j
      - name: Unit test Python
        run: |
          cd ${{ github.workspace }}
          pip3 install -r requirements.txt
          pip3 install -e .
          pytest tests/ --cov=godrick
      - name: Unit test CPP
        run: |
          cd ${{ github.workspace }}/build
          ctest --output-on-failure
      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
          name: python-coverage-comment-action
          # If you use a different name, update COMMENT_FILENAME accordingly
          path: python-coverage-comment-action.txt


